### ISSUE TITLE
运行 npm run dev 报错

### ISSUE THREAD

**Issue by yongpz** [shanyuhai123/vuepress-plugin-auto-sidebar#4]
开发者, 您好

使用您的插件在执行`npm run dev`时,有以下提示, 且无法看到侧边栏, 主题未使用默认主题, 而是使用 *reco* .

```
TypeError: Cannot read property 'split' of undefined
    at getMenuPath (/home/node/blogHome/node_modules/_vuepress-plugin-auto-sidebar@1.2.0@vuepress-plugin-auto-sidebar/lib/utils.js:2:46)
    at /home/node/blogHome/node_modules/_vuepress-plugin-auto-sidebar@1.2.0@vuepress-plugin-auto-sidebar/index.js:18:19     at Array.map (<anonymous>)
    at ready (/home/node/blogHome/node_modules/_vuepress-plugin-auto-sidebar@1.2.0@vuepress-plugin-auto-sidebar/index.js:16:30)
    at AsyncOption.asyncApply (/home/node/blogHome/node_modules/_@vuepress_core@1.3.0@@vuepress/core/lib/node/plugin-api/abstract/AsyncOption.js:33:21)
    at async PluginAPI.applyAsyncOption (/home/node/blogHome/node_modules/_@vuepress_core@1.3.0@@vuepress/core/lib/node/plugin-api/index.js:277:5)
    at async App.process (/home/node/blogHome/node_modules/_@vuepress_core@1.3.0@@vuepress/core/lib/node/App.js:123:5)      at async dev (/home/node/blogHome/node_modules/_@vuepress_core@1.3.0@@vuepress/core/lib/index.js:17:3)
```

另文件结果如下

```
docs
├── .vuepress
│   ├── public
│   │   └── *.png
│   ├── config.js
├── netcdf-python
│   ├── netCDF4-python.md
│   └── README.md
└── README.md
```

感谢

**Comment by shanyuhai123** [comment]
您好，由于 reco 主题使用 `plugin-blog` 插件渲染了非 md 文件生成的路径导致以上的问题，现已更新。

**Comment by shanyuhai123** [comment]
根据 reco 主题默认配置[测试结果](https://sm.ms/image/j2RAQxSbf3uFnWU) （由于网络问题，使用了外部图床）

**Comment by yongpz** [comment]
已成功使用, 另外请问, 该拓展是否支持目录遍历, 此拓展的`readme`感觉是支持的, 可是示例中的配置感觉不支持.

感谢

**Comment by shanyuhai123** [comment]
您好，在上面提供的截图示例目录层级为 `docs>views>category1>2019`。
不太理解您说的目录遍历，可否举个例子说一下。

**Comment by yongpz** [comment]
重新查看了你的示例 [前端->JAVASCRIPT](https://docs.shanyuhai.top/frontend/javascript/invocation-expression.html#%E8%AF%B4%E6%98%8E) 发现您的分组是通过 `autoGroup-1: 分组名称` 文件头提供的, 被我误认为了是基于目录分级(如下)实现的

```
docs
├── 前端
│   ├── JAVASCRIPT
│   │   └── 数组方法
│   │   │   └── ***.md
│   │   └── 对象方法
│   │   │   └── ***.md
│   │   └── 字符串方法
│   │   │   └── ***.md
│   ├── ***
│   ├── ***
│   ├── ***
│   └── README.md
```

***

原问题已经不是问题了, 因为我正在为我的文章添加分组, 原问题应该是: 

```
docs
├── A
│   ├── a
│   │   └── a1.md
│   ├── b
│   │   └── b1.md
│   └── README.md
├── ***
└── README.md
```

这个目录得到的 关于 `A` 的侧边栏结果**是否是**

```
A
├── a
│   └── a1
├── b
    └── b1
```

此外是否有根据目录自动对侧边栏分组开发计划呢

谢谢, 插件使用十分方便

**Comment by shanyuhai123** [comment]
上面的结果是的。
早期有考虑过插件配置处添加正则来便于分组，但正则匹配 md 文件名或标题都会导致其需要统一规范，不太符合常情，而且随着 md 文件的增多很容易导致复杂的正则或者干脆切换为数组(列表)的形式。而且增删文章后还得频繁去更新插件的配置，这种糟糕的体验还不如直接在文章的头部添加配置。

**Comment by shanyuhai123** [comment]
抱歉看错了，上面的结果是错的，只会跟踪到最后一层目录。
`/A`、`/A/a`、`/A/b` 已经属于不同的路由了。A 只会显示它自己下面的 md 文件，不过不推荐这么使用，在  [提问5](https://github.com/shanyuhai123/vuepress-plugin-auto-sidebar#5-%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E6%8E%A8%E8%8D%90%E7%9B%AE%E5%BD%95%E6%96%87%E4%BB%B6%E5%90%8C%E7%BA%A7%E5%AD%98%E5%9C%A8) 有说明其存在的问题。

**Comment by yongpz** [comment]
了解了, 感谢
